### ISSUE TITLE
problem in login with email address or phone number

### ISSUE THREAD

**Issue by HAsadian** [MahStudio/Winsta#15] opened 2018-11-12 09:36 UTC
When I login with email address or phone number, I see a blank home page. Also I can't see my profile and even its picture. App is not connected to my account in fact.

**Comment by NGame1** [comment] 2018-11-14 10:01
Currently, we are working on a fix for this bug.
This bug caused by an issue in our API library and will notify about the fix and release time.

**Comment by NGame1** [comment] 2018-11-14 10:29
Logging in using Email and Phone number has been fixed and now working.
The fix coming after the release in an update.
Thanks for being a part of our development.

**Closed** 2018-11-14 10:29 UTC
Labels: Working on it, bug
